### ISSUE TITLE
Generazione file di ci da ChatGPT

### ISSUE THREAD

**Issue by TheCris94** [gPiscopo3/Ingegneria-del-Software-2023#6]
Il workflow interrompe la build se i test non vanno a buon fine

``` 
name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assumi che ci sia un file requirements.txt

    - name: Run pytest
      run: |
        pytest

    - name: Check test status
      run: |
        test_exit_code=$?
        if [ $test_exit_code -ne 0 ]; then
          echo "Tests failed. Exiting with code $test_exit_code"
          exit $test_exit_code
        fi
```
